export const USER_LOGIN_ACTIONS = [
  "USER_LOGIN_REQUEST",
  "USER_LOGIN_SUCCESS",
  "USER_LOGIN_FAIL",
  "USER_LOGOUT",
]
export const USER_REGISTER_ACTIONS = [
  "USER_REGISTER_REQUEST",
  "USER_REGISTER_SUCCESS",
  "USER_REGISTER_FAIL",
]
export const USER_DETAILS_ACTIONS = [
  "USER_DETAILS_REQUEST",
  "USER_DETAILS_SUCCESS",
  "USER_DETAILS_FAIL",
]
export const USER_UPDATE_PROFILE_ACTIONS = [
  "USER_UPDATE_PROFILE_REQUEST",
  "USER_UPDATE_PROFILE_SUCCESS",
  "USER_UPDATE_PROFILE_FAIL",
  "USER_UPDATE_PROFILE_RESET",
]
